version: '3.8'

services:
  php-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      # Mount entire project for development (hot reload)
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    container_name: php-exercises-app