services:
  - type: web
    name: php-exercises
    env: docker
  dockerfilePath: ./dockerfile
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html
  healthCheckPath: /php2/
    autoDeploy: true